#!/bin/sh

# Generated the same way the official OPNsense plugin framework does it
# (plugins/Mk/plugins.mk -> scripts-auto), because the plugin ships:
#   - src/opnsense/service/conf/actions.d  -> configd must be restarted
#   - src/opnsense/mvc/app/models          -> migrations + plugin configuration
#   - src/opnsense/service/templates/*/*   -> templates must be generated
#
# The previous package shipped "exit 0" here, so configd never learned about
# the kixdns actions, /etc/rc.conf.d/kixdns and /usr/local/etc/kixdns/pipeline.json
# were never generated and nothing could be started from the web interface.

if [ -f /usr/local/etc/rc.d/configd ]; then /usr/local/etc/rc.d/configd restart; fi
if [ -f /usr/local/opnsense/mvc/script/run_migrations.php ]; then /usr/local/opnsense/mvc/script/run_migrations.php OPNsense/KixDNS; fi
if [ -f /usr/local/etc/rc.configure_plugins ]; then echo "Reloading plugin configuration"; /usr/local/etc/rc.configure_plugins POST_INSTALL; fi
if [ -f /usr/local/sbin/configctl ]; then echo -n "Reloading template OPNsense/KixDNS: "; /usr/local/sbin/configctl template reload OPNsense/KixDNS; fi
if [ -f /usr/local/sbin/configctl ]; then echo -n "Reloading template OPNsense/Syslog: "; /usr/local/sbin/configctl template reload OPNsense/Syslog; fi

exit 0
